<html>
<head>
  <title>条款13：通过引用捕获异常</title>
  <basefont face="微软雅黑" size="2" />
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="exporter-version" content="Evernote Windows/307027 (zh-CN, DDL); Windows/6.1.0 (Win64);"/>
  <style>
    body, td {
      font-family: 微软雅黑;
      font-size: 10pt;
    }
  </style>
</head>
<body>
<a name="1554"/>
<h1>条款13：通过引用捕获异常</h1>

<div>
<span><div><font style="font-size: 14pt;">条款13：通过引用捕获异常</font></div><div><br/></div><div>让异常传递到catch子句中有三种方式：指针，传值，引用</div><div><br/></div><div>1.指针</div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.15);-en-codeblock:true;"><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">class exception { ... };          // 来自标准C++库（STL）<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">中的异常类层次</span></span></div><div><br/></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">void someFunction()</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">{</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  static exception ex;            // 异常对象</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  ...</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">throw &amp;ex; // 抛出一个指针，指向 ex</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  ...</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">}</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">void doSomething()</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">{</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  try {</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">    someFunction();               // 抛出一个 exception*</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  }</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  catch (exception *ex) {         // 捕获 exception*;</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">    ...                           // 没有对象被拷贝</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  }</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">}</span></div></div><div>全局和静态对象能保证控制权离开函数后，对象还能继续生存，往往会写成这样</div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.15);-en-codeblock:true;"><div>void someFunction()</div><div>{</div><div><span>    exception ex;</span><br/></div><div><span><span>    ..</span><br/></span></div><div><span><span>    throw &amp;ex;//抛出一个指针，指向已被释放的对象</span><br/></span></div><div>}</div></div><div>另一种抛出指针的方法是建立一个堆对象</div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.15);-en-codeblock:true;"><div>void someFunction()</div><div>{</div><div><span>    ..</span><br/></div><div><span><span>    throw new exception;//抛出一个指针，指向一个在堆中建立的对象。</span><br/></span></div><div>}</div></div><div>这避免了捕获一个指向已被释放对象的指针的问题，但是 catch子句的作者又面临一个令人头疼的问题：他们是否应该删除他们接受的指针？如果是在堆中建立的异常对象，那他们必须删除它，否则会造成资源泄漏。如果不是在堆中建立的异常对象，他们绝对不能删除它，否则程序的行为将不可预测。</div><div><br/></div><div>这也不符合c++语言本身的规范。四个标准的异常</div><div>（1）bad_alloc：当operator new不能分配足够的内存时</div><div>（2）bad_cast ：当dynamic_cast针对一个引用操作失败时，被抛出</div><div>（3）bad_typeid : 当dynamic_cast 对空指针进行操作时被抛抛出</div><div>（4）bad_exception：用于exception异常</div><div><br/></div><div>2.传值</div><div>传值能解决上述问题，但是会发生对象切割</div><div>即派生类的异常对象被做为基类异常对象捕获时，那它的派生类行为就被切掉了（sliced off）。这样的sliced对象实际上是一个基类对象：它们没有派生类的数据成员，而且当本准备调用它们的虚拟函数时，系统解析后调用的却是基类对象的函数。</div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.15);-en-codeblock:true;"><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">class exception {  </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">public:                            </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  virtual const char * what() throw();</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">                                    // 返回异常的简短描述.</span></div><div><span style="font-size: 9pt; font-family: Monaco;"> ... </span><span style="font-size: 9pt; font-family: Monaco;">                                </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">};                                 </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">// 参见条款 14)</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">class runtime_error: </span><span style="font-family: Monaco; font-size: 9pt;">public exception { ... };  </span></div><div><span style="font-family: Monaco; font-size: 9pt;"><br/></span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">class Validation_error: </span><span style="font-family: Monaco; font-size: 9pt;">public runtime_error<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"> </span><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">            // 客户自己加入个类</span></span></div><div><span style="font-family: Monaco; font-size: 9pt;"> { </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">public:</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  virtual const char * what() throw();</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">                                    // 重新定义在异常类中<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">虚拟函数</span></span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  ...                               </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">};                                    </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"><br/></span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">void someFunction()                 // 抛出一个 validation<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">异常</span></span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">{                                  </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  ...</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  if (a validation 测试失败) {</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">    throw Validation_error();</span></div><div><span>  }</span><br/></div><div><span>...</span></div><div><span>}</span></div><div><span><br/></span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">void doSomething()</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">{</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  try {</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">    someFunction();                 // 抛出 validation<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">异常</span></span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  }                                </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  catch (exception ex) {            //捕获所有标准异常类<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"> 或它的派生类</span></span></div><div><br/></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  cerr &lt;&lt; ex.what();                // 调用 exception::what(),</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  ...                               // 而不是Validation_error::what()</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">}    </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">}</span></div></div><div>3.引用</div><div>将上述改为</div><div style="box-sizing: border-box; padding: 8px; font-family: Monaco, Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; color: rgb(51, 51, 51); border-radius: 4px; background-color: rgb(251, 250, 248); border: 1px solid rgba(0, 0, 0, 0.15);-en-codeblock:true;"><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">void doSomething()</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">{</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  try {</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">    someFunction();                 // 抛出 validation</span><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">异常</span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  }                                </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  catch (exception ex) {            //捕获所有标准异常类</span><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"> 或它的派生类</span></div><div><br style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);"/></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  cerr &lt;&lt; ex.what();                // 调用 <span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">Validation_error::what()</span></span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">  ...                               // 而不是<span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">exception::what(),</span></span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">}    </span></div><div><span style="font-family: Monaco; font-size: 9pt; color: rgb(51, 51, 51);">}</span></div></div><div><br/></div></span>
</div></body></html> 